---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - name: {{ .Release.Name }}-dashboard
          port: 5601
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/rpc/configurator`)"
      services:
        - name: {{ .Release.Name }}-dashboard
          port: 50051
          scheme: h2c
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/rpc/blocker`)"
      services:
        - name: {{ .Release.Name }}-logstash
          port: 50051
          scheme: h2c

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-logstash
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - logstash
  routes:
    - kind: Rule
      match: HostSNI(`{{ .Values.ingress.host }}`)
      services:
        - name: {{ .Release.Name }}-logstash
          port: 5044
