apiVersion: v1
kind: Secret
metadata:
metadata:
  name: {{ include "securely.fullname" . }}-pullsecret
  labels:
    {{- include "securely.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}