---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-securely-filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /opt/securely/access.log
      fields:
        event.module: nginx
        event.dataset: nginx.access
        organization.name: {{ .Values.filebeat.organization_name}}
    - type: log
      paths:
        - /opt/securely/modsec_audit.log
      fields:
        event.module: modsecurity
        event.dataset: modsecurity.audit
        organization.name: {{ .Values.filebeat.organization_name}}
      multiline:
        pattern: "^-{2,3}[a-zA-Z0-9]{8}-{1,3}Z--$"
        negate: true
        match: before
    output.logstash:
      # The Logstash hosts
      hosts:
        {{ toYaml .Values.filebeat.logstash_hosts}}