{{- if eq .Values.securely_blocker.enabled true }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-securely-blocker
data:
  FILE: /opt/securely/blocker-db 
  {{- toYaml .Values.securely_blocker.config  | nindent 2}}
{{- end }}