---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-securely-nginx-modsec
data:
  MODSEC_AUDIT_LOG: /opt/securely/modsec_audit.log
  MODSEC_AUDIT_LOG_FORMAT: Native
  METRICSLOG:  /opt/securely/access.log
  {{- if .Values.nginx_modsec.config }}
  {{- toYaml .Values.nginx_modsec.config | nindent 2}}
  {{- end }}