apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-securely-proxy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: securely-proxy
  template:
    metadata:
      annotations:
        checksum/config-securely-nginx-modsec: {{ include (print $.Template.BasePath "/configmap-securely-nginx-modsec.yml") . | sha256sum }}
        checksum/config-securely-blocker: {{ include (print $.Template.BasePath "/configmap-securely-blocker.yml") . | sha256sum }}
        checksum/config-securely-secruleconfigurator: {{ include (print $.Template.BasePath "/configmap-securely-secruleconfigurator.yml") . | sha256sum }}
        checksum/config-securely-filebeat: {{ include (print $.Template.BasePath "/configmap-securely-filebeat.yml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: securely-proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: securely-volume
        emptyDir:
          sizeLimit: {{ .Values.volumes.securely_volume.sizeLimit }}
      - name: filebeat-config
        configMap:
          name: {{ .Release.Name }}-securely-filebeat
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: nginx-modsec
        image:  {{ .Values.nginx_modsec.image }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-securely-nginx-modsec
        volumeMounts:
        - name: securely-volume
          mountPath: /opt/securely
        {{- with .Values.nginx_modsec.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.nginx_modsec.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nginx_modsec.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nginx_modsec.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if eq .Values.securely_blocker.enabled true }}
      - name: securely-blocker
        image: {{ .Values.securely_blocker.image }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-securely-blocker
        volumeMounts:
        - name: securely-volume
          mountPath: /opt/securely
        {{- with .Values.securely_blocker.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.securely_blocker.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securely_blocker.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securely_blocker.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if eq .Values.securely_secruleconfigurator.enabled true }}
      - name: securely-secruleconfigurator
        image: {{ .Values.securely_secruleconfigurator.image }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-securely-secruleconfigurator
        volumeMounts:
        - name: securely-volume
          mountPath: /opt/securely
        {{- with .Values.securely_secruleconfigurator.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.securely_secruleconfigurator.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securely_secruleconfigurator.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securely_secruleconfigurator.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if eq .Values.filebeat.enabled true }}
      - name: filebeat
        image: {{ .Values.filebeat.image }}
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: securely-volume
          mountPath: /opt/securely
        - name: filebeat-config
          readOnly: true
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        {{- with .Values.filebeat.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.filebeat.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.filebeat.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.filebeat.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}