apiVersion: v1
kind: Service
metadata:
  name: {{ include "securely-proxy.fullname" . }}-securely-proxy
spec:
  selector:
    app.kubernetes.io/name: {{ include "securely-proxy.fullname" . }}
    app.kubernetes.io/instance: securely-proxy
  ports:
    - name: {{ include "securely-proxy.fullname" . }}-securely-proxy
      protocol: TCP
      port: 80
      targetPort: 80
