imageCredentials:
  registry: registry.securely.ai

dashboard:
  resources:
    requests:
      cpu: 50m
  replicaCount: 2
  maxUnavailable: 1

  imagePullSecrets:
    - name: securely-pullsecret

  env:
  - name: ELASTICSEARCH_USERNAME
    value: elastic
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: securely-es-elastic-user
        key: elastic
  - name: ELASTICSEARCH_HOSTS
    value: '["http://securely-es-http:9200"]'
  - name: XPACK_SECURITY_ENCRYPTIONKEY
    value: K1W1mjKbTbBivfeog9fx0L4WKj27nERr'

logstash:
  resources:
    requests:
      cpu: 250m
      memory: 1200Mi
    limits:
      cpu: 1000m 
  replicaCount: 2
  maxUnavailable: 1

  imagePullSecrets:
    - name: securely-pullsecret

  env: 
  - name: ES_USERNAME
    value: elastic
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: securely-es-elastic-user
        key: elastic
  - name: ES_HOST
    value: 'securely-es-http:9200'
  - name: GRPC_URL
    value: securely-dashboard:50051
  - name: xpack.monitoring.enabled
    value: 'false'
  - name: xpack.monitoring.elasticsearch.hosts
    value: '["http://securely-es-http:9200"]'
  - name: xpack.monitoring.elasticsearch.username
    value: elastic
  - name: xpack.monitoring.elasticsearch.password
    valueFrom:
      secretKeyRef:
        name: securely-es-elastic-user
        key: elastic

elasticsearch:
  version: "7.17.13"

  http:
    tls:
      selfSignedCertificate:
        disabled: true

traefik:
  deployment:
    lifecycle: 
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 10"]
  service:
    type: Service

  ingressClass:
    enabled: false

  providers:
    kubernetesCRD:
      enabled: true
      ingressClass: traefik-internal
    kubernetesIngress:
      enabled: false

  ingressRoute:
    dashboard:
      annotations: 
        kubernetes.io/ingress.class: traefik-internal
  rbac:
    enabled: true
    namespaced: true

  additionalArguments:
  - "--entryPoints.logstash.address=:5044/tcp"

  ports:
    logstash:
      port: 5044
      expose: true
      hostPort: 5044
      exposedPort: 5044
      protocol: TCP
      tls:
        enabled: true
  logs:
    access:
    enabled: true

ingress:
  host: exmaple.com